name: Juice Shop DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_pipeline:
    runs-on: ubuntu-24.04

    steps:
      # ------------------------
      # Checkout Source Code
      # ------------------------
      - name: Checkout Source Code
        uses: actions/checkout@v4

      #------------------------
      # Prepare Workspace
      #------------------------
      - name: Create reports directory
        run: mkdir -p reports

      # ------------------------
      # SAST: Semgrep
      # ------------------------
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto \
                  --json \
                  --output reports/semgrep.json

      - name: Verify Semgrep Report
        run: ls -la reports

      # ------------------------
      # Build Docker Image
      # ------------------------
      - name: Build Juice Shop Docker image
        run: docker build -t juice-shop:latest .

      # ------------------------
      # SCA: Trivy
      # ------------------------
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
          | sudo sh -s -- -b /usr/local/bin

      - name: Run Trivy (SCA)
        run: |
          trivy image juice-shop:latest \
            --format json \
            --output reports/trivy.json

      # ------------------------
      # Deploy Container
      # ------------------------
      - name: Run Juice Shop Container
        run: docker run -d --name juice-shop -p 3000:3000 juice-shop:latest

      # Wait for container to be ready
      - name: Wait for Juice Shop to start
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up"
              break
            fi
            echo "Waiting for Juice Shop..."
            sleep 3
          done

      # ------------------------
      # DAST: ZAP Baseline Scan
      # ------------------------
      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            --network=host \
            --user root \
            -v ${{ github.workspace }}:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://localhost:3000 \
              -x reports/zap-report.xml \
              -r reports/zap.html \
              -w reports/zap.md \
              -m 5 \
              -a || true
      - name: Verify ZAP Report
        run: ls -la reports

      #------------------------
      # Debug ZAP report
      #------------------------
      - name: Debug permissions
        run: |
          ls -la
          ls -la reports


      # ------------------------
      # Upload Reports to GitHub Artifacts
      # ------------------------
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/

      # ------------------------
      # Push Reports to DefectDojo
      # ------------------------
      - name: Upload ZAP to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=ZAP Scan" \
            -F "file=@reports/zap-report.xml" \
            -F "engagement=1" \
            -F "active=true" \
            -F "verified=false"

      - name: Upload Semgrep to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=Semgrep" \
            -F "file=@reports/semgrep.json" \
            -F "engagement=1" \
            -F "active=true" \
            -F "verified=false"

      - name: Upload Trivy to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "scan_type=Trivy Scan" \
            -F "file=@reports/trivy.json" \
            -F "engagement=1" \
            -F "active=true" \
            -F "verified=false"
