name: Juice Shop DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Juice Shop
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: |
          mkdir -p reports
          semgrep --config=auto --json --output reports/semgrep.json

      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin


      - name: Run Trivy
        run: trivy image --format json --output reports/trivy.json juice-shop:latest

      - name: Deploy container
        run: docker run -d --name juice-shop -p 3000:3000 juice-shop:latest

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.1
        with:
          target: 'http://localhost:3000'
          format: 'json'
          output: 'reports/zap.json'

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
